site_name: GapML CV
theme: readthedocs

repo_url: https://github.com/gapml/CV
site_url: https://gapml.github.io/CV/
site_description: 'Documentation for GapML CV.'

google_analytics: ['UA-124527631-2', 'gapml.github.io/CV/']

nav:
  - Home: index.md
# - About: about.md
# - Organization: org-os.md
# - Quick Start Guide: quick-start-guide.md
# - Tutorials:
#     - Computer Vision: tutorials/computer_vision.md
#     - Computer Vision advanced: tutorials/computer_vision_advanced.md
# - Specifications:
#     - Vision: specs/vision_spec.md